{{- if .Values.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  labels:
    projectname: {{ .Values.project }}
    environment: {{ .Values.environment }}
    servicename: {{ .Values.servicename }}
  name: {{ .Values.servicename }}
spec:
  ports:
    - port: {{ if eq .Values.servicename "redis" }} 6379 {{ else }} {{ .Values.service.port }} {{ end }}
      protocol: TCP
      targetPort: {{ if eq .Values.servicename "redis" }} 6379 {{ else }} {{ .Values.service.port }} {{ end }}
  selector:
    servicename: {{ .Values.servicename }}
  type: {{ .Values.service.type }}
{{- end }}