# Default values for docker-coin-prod.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

environment: prod
project: dockercoins
replicaCount: 1

image:
  registry: 127.0.0.1:32576
  tag: v0.1
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  webuiHost:  webui.192.168.33.111.nip.io