apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    projectname: {{ .Values.project }}
    environment: {{ .Values.environment }}
    servicename: hasher
  name: hasher
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      servicename: hasher
  template:
    metadata:
      labels:
        projectname: {{ .Values.project }}
        environment: {{ .Values.environment }}
        servicename: hasher
    spec:
      containers:
        - image: {{ .Values.image.registry }}/hasher:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: hasher
          env: 
            - name: PROJECT_NAME
              value: {{ .Values.project }}
            - name: ENVIRONMENT
              value: {{ .Values.environment }}
            - name: SERVICE_NAME
              value: hasher
          livenessProbe:
            httpGet:
              path: /
              port: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80