apiVersion: v1
kind: Service
metadata:
  labels:
    projectname: {{ .Values.project }}
    environment: {{ .Values.environment }}
    servicename: rng
  name: rng
spec:
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: {{ .Values.service.port }}
  selector:
    servicename: rng
  type: {{ .Values.service.type }}
