apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: rng
  labels:
    projectname: {{ .Values.project }}
    environment: {{ .Values.environment }}
    servicename: rng

spec:
  selector:
    matchLabels:
      servicename: rng
  template:
    metadata:
      labels:
        projectname: {{ .Values.project }}
        environment: {{ .Values.environment }}
        servicename: rng
    spec:
      containers:
        - image: {{ .Values.image.registry }}/rng:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: rng
          env: 
            - name: PROJECT_NAME
              value: {{ .Values.project }}
            - name: ENVIRONMENT
              value: {{ .Values.environment }}
            - name: SERVICE_NAME
              value: rng
          livenessProbe:
            httpGet:
              path: /
              port: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80