apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    projectname: {{ .Values.project }}
    environment: {{ .Values.environment }}
    servicename: worker
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      servicename: worker
  template:
    metadata:
      labels:
        projectname: {{ .Values.project }}
        environment: {{ .Values.environment }}
        servicename: worker
    spec:
      containers:
        - image: {{ .Values.image.registry }}/worker:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: worker
          env: 
            - name: PROJECT_NAME
              value: {{ .Values.project }}
            - name: ENVIRONMENT
              value: {{ .Values.environment }}
            - name: SERVICE_NAME
              value: worker
          livenessProbe:
            exec:
              command:
              - ps
              - aux | grep python | grep -v grep
          readinessProbe:
            exec:
              command:
              - ps
              - aux | grep python | grep -v grep